---
name: CI
on:
  pull_request:
  push:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  test_go:
    name: Go tests
    runs-on: ubuntu-latest
    container:
      image: golang:1.24.1-alpine
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: go test ./...
